Add image stream for JDK8 + RHEL8
jboss-container-images/jboss-eap-openshift-templates pull request #60
Opened 2023-02-22 14:45 UTC by rdnovell

Issue: https://issues.redhat.com/browse/JBEAP-24491
Signed-off-by: Ruben Dario Novelli [rnovelli@redhat.com](mailto:rnovelli@redhat.com)

I created a new file "eap74-openjdk8-rhel8-image-stream.json" using "eap74-openjdk8-image-stream.json" as source and change only the references from rhel7 to rhel8

diff eap74-openjdk8-rhel8-image-stream.json as rhel8-file eap74-openjdk8-image-stream.json as rhel7-file

rhel8-file= "name": "jboss-eap74-openjdk8-rhel8-openshift-image-streams",
rhel7-file= "name": "jjboss-eap74-openjdk8-openshift-image-streams",

rhel8-file= "description": "ImageStream definition for JBoss Enterprise Application Platform 7.4.0 with OpenJDK 8 and RHEL 8",
rhel7-file= "description": "ImageStream definition for JBoss Enterprise Application Platform 7.4.0 with OpenJDK 8",

rhel8-file= "name": "jboss-eap74-openjdk8-rhel8-openshift",
rhel7-file= "name": "jboss-eap74-openjdk8-openshift",

rhel8-file= "openshift.io/display-name": "JBoss EAP 7.4.0 with OpenJDK 8 and RHEL 8",
rhel7-file= "openshift.io/display-name": "JBoss EAP 7.4.0 with OpenJDK 8",

rhel8-file= "description": "The latest available build of JBoss EAP 7.4 builder image with OpenJDK 8 and RHEL8.",
rhel7-file= "description": "The latest available build of JBoss EAP 7.4 builder image with OpenJDK 8.",

rhel8-file= "openshift.io/display-name": "JBoss EAP 7.4 with OpenJDK8 and RHEL 8"
rhel7-file= "openshift.io/display-name": "JBoss EAP 7.4 with OpenJDK8"

rhel8-file= "name": "registry.redhat.io/jboss-eap-7/eap74-openjdk8-openshift-rhel8:latest"
rhel7-file= "name": "registry.redhat.io/jboss-eap-7/eap74-openjdk8-openshift-rhel7:latest"

rhel8-file= "description": "The latest available build of JBoss EAP 7.4.0 builder image with OpenJDK 8 and RHEL8.",
rhel7-file= "description": "The latest available build of JBoss EAP 7.4.0 builder image with OpenJDK 8.",

rhel8-file= "openshift.io/display-name": "JBoss EAP 7.4.0 with OpenJDK8 and RHEL8"
rhel7-file= "openshift.io/display-name": "JBoss EAP 7.4.0 with OpenJDK8"

rhel8-file= "name": "registry.redhat.io/jboss-eap-7/eap74-openjdk8-openshift-rhel8:latest"
rhel7-file= "name": "registry.redhat.io/jboss-eap-7/eap74-openjdk8-openshift-rhel7:latest"

rhel8-file= "name": "jboss-eap74-openjdk8-rhel8-runtime-openshift",
rhel7-file= "name": "jboss-eap74-openjdk8-runtime-openshift",

rhel8-file= "openshift.io/display-name": "JBoss EAP 7.4.0 Runtime Image with OpenJDK 8 and RHEL8",
rhel7-file= "openshift.io/display-name": "JBoss EAP 7.4.0 Runtime Image with OpenJDK 8",

rhel8-file= "description": "The latest available build of JBoss EAP 7.4 runtime image with OpenJDK 8 and RHEL8",
rhel7-file= "description": "The latest available build of JBoss EAP 7.4 runtime image with OpenJDK 8",

rhel8-file= "openshift.io/display-name": "JBoss EAP 7.4 with OpenJDK 8 (Runtime Image) and RHEL8"
rhel7-file= "openshift.io/display-name": "JBoss EAP 7.4 with OpenJDK 8 (Runtime Image)"

rhel8-file= "name": "registry.redhat.io/jboss-eap-7/eap74-openjdk8-runtime-openshift-rhel8:latest"
rhel7-file= "name": "registry.redhat.io/jboss-eap-7/eap74-openjdk8-runtime-openshift-rhel7:latest"

rhel8-file= "description": "The latest available build of JBoss EAP 7.4.0 runtime image with OpenJDK 8 and RHEL8",
rhel7-file= "description": "The latest available build of JBoss EAP 7.4.0 runtime image with OpenJDK 8",

rhel8-file= "openshift.io/display-name": "JBoss EAP 7.4.0 with OpenJDK 8 (Runtime Image) and RHEL8"
rhel7-file= "openshift.io/display-name": "JBoss EAP 7.4.0 with OpenJDK 8 (Runtime Image)"

rhel8-file= "name": "registry.redhat.io/jboss-eap-7/eap74-openjdk8-runtime-openshift-rhel8:latest"
rhel7-file= "name": "registry.redhat.io/jboss-eap-7/eap74-openjdk8-runtime-openshift-rhel7:latest"

2023-02-22 15:05 UTC, luck3y requested changes

2023-02-22 15:05 UTC, luck3y commented on eap74-openjdk8-rhel8-image-stream.json
> +            "description": "ImageStream definition for JBoss Enterprise Application Platform 7.4.0 with OpenJDK 8 and RHEL 8",
I don't really like us having the base OS image name in here, as we could just move it to UBI 9 and everything would still likely be the same for customers, so I'd suggest only having it in the imagestream filename and this first description. The description, I'd suggest read: ""ImageStream definition for JBoss Enterprise Application Platform 7.4.0 with OpenJDK 8 based on UBI 8"

2023-02-22 15:05 UTC, luck3y commented on eap74-openjdk8-rhel8-image-stream.json
> +                    "openshift.io/display-name": "JBoss EAP 7.4.0 with OpenJDK 8 and RHEL 8",
See comment above, but if we have to specify, then its UBI 8, not RHEL 8.

2023-02-22 15:05 UTC, luck3y commented on eap74-openjdk8-rhel8-image-stream.json
> +                    "openshift.io/display-name": "JBoss EAP 7.4.0 with OpenJDK 8 and RHEL 8",
And same with rest of the display names.

2023-02-22 20:03 UTC, luck3y commented
@jmesnil FYI

2023-02-23 10:41 UTC, rdnovell commented
I edit descriptions and display-name. Now we have only the reference to rhel8 or ubi8 in the "List".metadata.name /             "ImageStream".metadata.name and "List".metadata.annotations.description

2023-03-27 14:30 UTC, luck3y approved these changes

2023-03-27 14:31 UTC, merged